project:
  type: website
  output-dir: .


website:
  title: "EPPS 6356 Data Visualization"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Homework
        menu:
          - href: hm1.qmd
            text: Homework 1
          - href: hm2.qmd
            text: Homework 2
          - href: hm3.qmd
            text: Homework 3
          - href: hm4.qmd
            text: Homework 4
          - href: hm5.qmd
            text: Homework 5
          - href: hm6.qmd
            text: Homework 6
      - text: Final Project
        menu:
          - href: proposal.qmd
            text: Proposal
          - href: final_project.qmd
            text: Final Report

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


